### ISSUE TITLE
Bug - Impossible to restore addresses

### ISSUE THREAD

**Issue by Technifocal** [Samourai-Wallet/samourai-dojo#39]
@pxsocs is having issues on Telegram with importing new addresses and getting their balance, and I think(?) I might know why:

1. [In getWalletInfo()](https://github.com/Samourai-Wallet/samourai-dojo/blob/b4cd156301093659ff487fff48fa5e844959fcb7/lib/wallet/wallet-service.js#L62) we add all new `pubkeys` to the DB
2. On the next line, we call [walletInfo.ensureAddresses()](https://github.com/Samourai-Wallet/samourai-dojo/blob/b4cd156301093659ff487fff48fa5e844959fcb7/lib/wallet/wallet-info.js#L76-L88)
3. `ensureAddresses()` checks every address we're attempting to import against those in the database, it then calls [addrService.restoreAddresses()](https://github.com/Samourai-Wallet/samourai-dojo/blob/b4cd156301093659ff487fff48fa5e844959fcb7/lib/wallet/wallet-info.js#L87) on all the addresses that are **_NOT_** in the database

Only issue is, all the addresses _ARE_ in the database because we just imported them in step 1.

Commenting out the line referenced in step 1 resolves this issue. Now `multiaddr` takes awhile to import new addresses:

![image](https://user-images.githubusercontent.com/20205745/61157034-da1bc180-a4ec-11e9-89e3-db02a7734253.png)

And returns their balances:

![image](https://user-images.githubusercontent.com/20205745/61157045-e1db6600-a4ec-11e9-8555-b658d1ab36e7.png)

**Comment by kenshin-samourai** [comment]
addresses are restored by passing the addresses to /multiaddr through the "active" parameter.

as you will notice step 1 doesn't process active addresses.

others parameters of the endpoint (new, bip49, bip84, pubkey) are for new addresses/xpubs.

**Comment by pxsocs** [comment]
I'm going to try to detail here the steps I'm taking. Both with the Dojo Maintenance Tool as well as with the API and the results I'm getting. I just can't get the transaction details correctly or reliably. Not sure what I'm missing. Tried many different things and still not getting reliable transaction data.

## Importing with the Maintenance Tool
### Test 1 
#### Sample random address: [3BMEXqGpG4FxBA1KWhRFufXfSTRgzfDBhJ](https://oxt.me/address/3BMEXqGpG4FxBA1KWhRFufXfSTRgzfDBhJ)
OXT Shows the following activity:
![Screen Shot 2019-07-13 at 6 41 43 PM](https://user-images.githubusercontent.com/40473443/61176837-27a43700-a59e-11e9-866e-65bc7fa5636c.png)

1. Click on Tab _MULTIADDR_ and enter: 
`active=3BMEXqGpG4FxBA1KWhRFufXfSTRgzfDBhJ`
Result:
![Screen Shot 2019-07-13 at 6 45 54 PM](https://user-images.githubusercontent.com/40473443/61176858-794cc180-a59e-11e9-9cce-40294491dade.png)
Notice the hash of the single transaction is the hash of the last transaction in this address (on July 3rd).

__Result with this address__: Correct Balance (since last tx is ok) but only 1 tx listed

### Test 2
#### Sample random address: [1Ckq6GXGWMoALRV4hLTcoJTKX5rVUDbNLz](https://oxt.me/address/1Ckq6GXGWMoALRV4hLTcoJTKX5rVUDbNLz)
![Screen Shot 2019-07-13 at 7 02 10 PM](https://user-images.githubusercontent.com/40473443/61176970-bfa32000-a5a0-11e9-84d7-ed1fad5afab2.png)

1. Click on Tab _MULTIADDR_ and enter: 
`active=1Ckq6GXGWMoALRV4hLTcoJTKX5rVUDbNLz`
Result:
![Screen Shot 2019-07-13 at 7 03 42 PM](https://user-images.githubusercontent.com/40473443/61176978-f6793600-a5a0-11e9-990c-c1fceebe2d5e.png)

__Result with this address__: Correct Balance (zero) but no tx listed.

#### Alternative method tried with the Maintenance Tool
. Step 1: MULTIADDR: `new=[add]`
. Step 2: ADDR. RESCAN
. Step 3: MULTIADDR: `pubkey=[add]`
__This method works some times returning all txs (but doesn't work consistently)__

------------------------------------------------------
## Importing with the API
### Test 1 
#### Sample random address: [1JFzLv56GqDgxg8S88t9Mt46x19sD9P9zP](https://oxt.me/address/1JFzLv56GqDgxg8S88t9Mt46x19sD9P9zP)
![Screen Shot 2019-07-13 at 7 09 53 PM](https://user-images.githubusercontent.com/40473443/61177039-e01faa00-a5a1-11e9-928e-5098f85edafb.png)

1. Send Get request:
`GET /multiaddr?active=1JFzLv56GqDgxg8S88t9Mt46x19sD9P9zP&at=[token]`
API LOG Returns:
```
Importing 1JFzLv56GqDgxg8S88t9Mt46x19sD9P9zP
Got 0 transactions
Imported 1 addresses in 44.3s (44335 ms/addr)
```
2. List Transactions:
`GET /txs?active=1JFzLv56GqDgxg8S88t9Mt46x19sD9P9zP&at=[token`
Returns:
`{"n_tx": 0, "address": "1JFzLv56GqDgxg8S88t9Mt46x19sD9P9zP", "balance": 0}`

__Result with this address__: No Txs seem to be imported.

**Comment by Technifocal** [comment]
@kenshin-samourai Fair enough, using `active` seems to work. I feel like the [documentation](https://github.com/Samourai-Wallet/samourai-dojo/blob/master/doc/GET_multiaddr.md) for `active` could be improved as it does not mention that they will be imported at all:

>active - string - A pipe-separated list of extended public keys and/or loose addresses and/or pubkeys (xpub1|address1|address2|pubkey1|...)

@pxsocs Dojo is only able to acquire UTXOs, not STXOs, without using `oxt.me` (which is disabled by default for privacy reasons, I believe). This is a limitation of bitcoind's [scantxoutset](https://bitcoincore.org/en/doc/0.18.0/rpc/blockchain/scantxoutset/)

**Comment by pxsocs** [comment]
@Technifocal that would explain the missing transactions. Thanks.

**Comment by kenshin-samourai** [comment]
@Technifocal ACK for the doc

@pxsocs Technifocal is 100% correct about the limitations of dojo when using bitcoind's scantxoutset.
