### ISSUE TITLE
nginx exited with code 1

### ISSUE THREAD

**Issue by theotherside** [Samourai-Wallet/samourai-dojo#45]

**Comment by theotherside** [comment]
On first run connecting to local node

**Comment by theotherside** [comment]
Maybe need to edit the docker-compose.yaml file, I'm not sure of what values to use

**Comment by coinsurenz** [comment]
same issue here- I'm trying to run dojo with my full node.  I have followed the steps here [https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_advanced_setups.md](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_advanced_setups.md))

I get as far as 
Initialized 1_db.sql
Initialized docker-bitcoind.conf
Initialized docker-mysql.conf
Initialized docker-node.conf
tor is up-to-date
db is up-to-date
Recreating nodejs ... done
Recreating nginx  ... done
Attaching to nginx, nodejs, db, tor
 then it will hang and eventually return

**Comment by LaurentMT** [comment]
May you share these information about your setup?
- hardware (laptop, raspi, etc),
- OS,
- type of Dojo setup (default, advanced setup like Dojo running on top of an external bitcoind),
- version of Dojo installed.

@theotherside docker-compose.yaml file shouldn't be modified.

@coinsurenz This Tor log is "fine".  It happens from time to time.

**Comment by theotherside** [comment]
Raspi3 running bitcoind.
Windows running the latest release of dojo. 
So I am trying to connect windows running dojo to my raspiblitz backend.

**Comment by LaurentMT** [comment]
@theotherside May you check the logs of the Tracker with this command?
```
./dojo.sh logs tracker -d error -n 500
```

**Comment by theotherside** [comment]
Empty. 
![C924BD65-1034-4373-8825-961F8C6A8A9E](https://user-images.githubusercontent.com/1767817/62481861-3cc54d80-b779-11e9-9f29-e818141ec091.jpeg)

**Comment by LaurentMT** [comment]
@theotherside IMy best guess for now is that nginx returns a timeout because it's waiting for an answer from nodejs which doesn't return a response for whatever reason.

May you check which containers are correctly running with this command?
```
docker ps
```

**Comment by theotherside** [comment]
Attached
![0217419C-1628-4CB2-BF8D-5E5E7617C7B0](https://user-images.githubusercontent.com/1767817/62483006-48664380-b77c-11e9-8827-028d9b4bff79.jpeg)

**Comment by LaurentMT** [comment]
I think the cause of your problem is that nodejs can't communicate with your full node. It's likely caused by a problem of configuration. Here are a few things that you should check:
- You need to determine the IP address of your full node on the local network. Let's note it <ip_bitcoin_lan>,
- You need to determine the IP address of docker on your LAN (on a linux box it would be the IP address on the LAN of the box running but I'm not sure if it's similar on Win10 or if Docker is running in a VM which has its own IP address). Let's note this IP address <ip_docker_lan>
- You should check that the bitcoin.conf of your full node is correctly configured and that these entries are set:
```
listen=1
server=1
txindex=1
rpcallowip=<ip_docker_lan> (or an IP range allowing the <ip_docker_lan>)
rpcbind=<ip_bitcoin_lan>
rpcport=<rpc_port>
rpcuser=<rpc_user>
rpcpassword=<rpc_password>
zmqpubhashblock=tcp://<ip_bitcoin_lan>:<zmq_port_hash_blk>
zmqpubrawtx=tcp://<ip_bitcoin_lan>:<zmq_port_raw_txs>
```
- You should check that your Dojo is correctly configured by editing <dojo_dir>/docker/my-dojo/conf/docker-bitcoind.conf.tpl and by checking the following lines
```
BITCOIND_RPC_USER=<rpc_user>
BITCOIND_RPC_PASSWORD=<rpc_password>
BITCOIND_INSTALL=off
BITCOIND_IP=<ip_bitcoin_lan>
BITCOIND_RPC_PORT=<rpc_port>
BITCOIND_ZMQ_RAWTXS=<zmq_port_hash_blk>
BITCOIND_ZMQ_BLK_HASH=<zmq_port_raw_txs>
```
Note: Youll have to restart your bitcoind and your Dojo if some of these properties need to be modified.

**Comment by theotherside** [comment]
Alright, thanks for the information. I will look at it later and get back with any results.

**Comment by theotherside** [comment]
listen=1 was missing. I am going to start over and try again.
