### ISSUE TITLE
Websocket API 

### ISSUE THREAD

**Issue by waterdrop01** [Samourai-Wallet/samourai-dojo#48]
Hi,

is there a websocket API to notify the client that a wallet balance changed?

Thanks!

**Comment by LaurentMT** [comment]
Indeed, Dojo provides a websocket API allowing clients to subscribe to two types of notifications:
- notifications of new blocks,
- notifications of new transactions related to a given address or xpub.

AFAIK, this API isn't documented but here are a few elements:
- access to this API is authenticated. It means that you first need to authenticate to your Dojo (see this [doc](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/POST_auth_login.md)) in order to receive an access token and a refresh token.
- subscription to notifications is done by sending a request to the url `<onion_address>/v2/inv` with a websocket client.

Data sent for a subscription request are structured as a JSON encoded in UTF-8:

```
// JSON for a subscription to notifications of new blocks
{
  "op":"block_sub",
  "at":"<your_access_token>"
}

// JSON for a subscription to notifications of new transactions
{
  "op":"addr_sub",
  "addr": "<address_or_xpub>",
  "at":"<your_access_token>"
}
```

**Comment by waterdrop01** [comment]
Thanks @LaurentMT, I will try and close the issue if it's working for me!
