### ISSUE TITLE
Is it possible to not use Tor and Nginx?

### ISSUE THREAD

**Issue by waterdrop01** [Samourai-Wallet/samourai-dojo#51]
Hello,

I'm wondering if after commenting out **nginx** service and **tor** service in the [docker-compose.yml](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/docker/my-dojo/docker-compose.yaml), everything will still work fine?

Or are these two services a hard requirement?

Thank you!

**Comment by kenshin-samourai** [comment]
these services are required for multiple reasons:
- communications of clients (e.g.: samourai wallet) with the api through tor
- communications of bitcoind with the bitcoin network through tor
- access to the maintenance tool

commenting the 2 services will break the build of docker containers because some services rely on them (e.g. bitcoind)

out of curiosity, why do you want to deactivate these 2 services?

**Comment by waterdrop01** [comment]
Thanks for the reply.

I'm planning to use Dojo's wallet API to track/monitor movements on personal HD wallets.
As they are going to be public HD wallets, I thought that the privacy level brought by Tor may not be necessary, and disabling it may save some CPU/RAM. But that's totally fine, it's clearly not a hard requirement in my case.

However, being able to run both testnet and mainnet on the same machine would be really nice to have, and Tor may be the problem here, is it?

Thanks @kenshin-samourai !
