### ISSUE TITLE
Using Dojo with Electrum Personal Server

### ISSUE THREAD

**Issue by 4NobleTruths** [Samourai-Wallet/samourai-dojo#92]
**Describe the issue**

This is regarding Electrum Personal Server using Dojo as its bitcoin node:
https://github.com/chris-belcher/electrum-personal-server/issues/148

In dojo bitcoind configuration, seems that RPC can be configured not to go through tor.

So, dojo and eps are actually incompatible at this point, only because of walletdisabled setting.
Is that right?

**Desktop (please complete the following information):**
 - OS: Debian 9
 - Dojo Version 1.2.0
 - Dojo Advanced Setups used none

**Comment by LaurentMT** [comment]
Indeed, the bitcoind instance installed by Dojo has a disabled wallet and its RPC API isn't served through Tor (it's intended to be used by clients running on the same host as Dojo or on the local network, if you feel confident about the security of your local network).

If your goal is to use a same bitcoind for both Dojo and EPS, my recommendation would be to install an independent bitcoind (with an activated wallet) and to configure your Dojo for running with an external bitcoind (see this section of the [doc](https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/doc/DOCKER_advanced_setups.md#external_bitcoind))

This advanced setup of Dojo is a bit more involved that the basic setup because you must properly configure bitcoind and Dojo with correct network info (IP addresses, ports,etc) and you must be sure that no firewall is blocking the communications between the 2 softwares. But it's definitely possible and it definitely works.

**Comment by LaurentMT** [comment]
Closed for inactivity
